### ISSUE TITLE
ZylonMCMod v1.0 Roadmap

### ISSUE THREAD

**Issue by Pramire** [ZylonMC/UnraveledMCMod#1]
- [ ] Custom Tablist
- [ ] Developers can be added in the config.yml
- [ ] Co-Owner rank from config.yml
- [ ] Architect rank from config.yml
- [ ] Eternal rank from config.yml
- [ ] Buildworld only accessiable by staff and architects
- [ ] Punishment GUI
- [ ] Punishment commands only from console
- [ ] Ban message configured from config.yml
- [ ] Discord bot support
- [ ] Shop
- [ ] Admin list divided into ranks
- [ ] Login message length restriction
- [ ] Ranks Sapphire, Amythest, Ruby, Eternal (SA, STA, SRA, EXEC)
- [ ] Player blacklist
- [ ] Staff file
- [ ] Permban file
- [ ] Admin command gui
- [ ] Admin kit gui (Logstick etc)
- [ ] Logstick

More to come!
